Work Flow

Credit card data -> Data-> pre Processing -> Data analysis -> Evaluation -> Logistic Regression Model -> train Test Split

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first five rows of dataset
# class = 1(fraud transaction) class = 0 (good transaction)
# amount column denote total amount extraction using credit card
# this dataset is about different transaction is made by the using different credit card
#Principal Component Analysis (PCA) is a dimensionality reduction technique used in machine learning
#and statistics to reduce the number of features or dimensions in a dataset while retaining as much relevant
#information as possible. The main goal of PCA is to transform the original features into a new set of features called
#principal components, which are orthogonal (uncorrelated) and capture the maximum variance in the data.

#Confidentiality of a user refers to the protection of sensitive information and data provided by the user, ensuring that only authorized individuals or entities have access to it, maintaining privacy and preventing unauthorized disclosure.
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.shape

(263383, 31)

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263383 entries, 0 to 263382
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    263383 non-null  float64
 1   V1      263383 non-null  float64
 2   V2      263383 non-null  float64
 3   V3      263383 non-null  float64
 4   V4      263383 non-null  float64
 5   V5      263383 non-null  float64
 6   V6      263383 non-null  float64
 7   V7      263383 non-null  float64
 8   V8      263383 non-null  float64
 9   V9      263383 non-null  float64
 10  V10     263383 non-null  float64
 11  V11     263383 non-null  float64
 12  V12     263383 non-null  float64
 13  V13     263383 non-null  float64
 14  V14     263383 non-null  float64
 15  V15     263383 non-null  float64
 16  V16     263383 non-null  float64
 17  V17     263383 non-null  float64
 18  V18     263383 non-null  float64
 19  V19     263383 non-null  float64
 20  V20     263382 non-null  float64
 21  V21     263382 non-null  float64
 22  V22     263382 non-null  float64
 23  V23     263382 non-null  float64
 24  V24     263382 non-null  float64
 25  V25     263382 non-null  float64
 26  V26     263382 non-null  float64
 27  V27     263382 non-null  float64
 28  V28     263382 non-null  float64
 29  Amount  263382 non-null  float64
 30  Class   263382 non-null  float64
dtypes: float64(31)
memory usage: 62.3 MB

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
263378,160930.0,1.875754,-0.546235,-0.012430,0.299645,-0.745193,0.117545,-0.855484,0.160214,1.196884,...,0.141402,0.551345,0.186820,-0.382094,-0.371877,-0.409563,0.057220,-0.032903,36.40,0.0
263379,160930.0,1.920392,0.308281,-2.692298,1.054117,1.919784,1.101515,0.307974,0.271223,-0.046354,...,0.037938,0.372764,-0.004101,-1.077150,0.331907,-0.409093,0.039049,-0.050478,5.45,0.0
263380,160930.0,-4.340723,3.109247,-1.148444,-0.159526,-2.645835,-0.592827,-2.261003,3.138933,-0.932311,...,0.274750,-0.485363,0.080569,-0.086778,0.416046,-0.487368,-1.820859,-0.515789,20.56,0.0
263381,160930.0,1.585693,-1.029592,-1.540494,0.125769,0.006604,0.060928,0.153937,-0.044163,0.817159,...,-0.000736,-0.325880,-0.003948,0.316699,-0.122789,-0.137771,-0.073642,-0.023522,233.78,0.0
263382,160930.0,-1.611418,1.659217,-0.977356,-0.746698,-0.183138,-0.636617,0.025867,0.839185,-0.328529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263383 entries, 0 to 263382
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    263383 non-null  float64
 1   V1      263383 non-null  float64
 2   V2      263383 non-null  float64
 3   V3      263383 non-null  float64
 4   V4      263383 non-null  float64
 5   V5      263383 non-null  float64
 6   V6      263383 non-null  float64
 7   V7      263383 non-null  float64
 8   V8      263383 non-null  float64
 9   V9      263383 non-null  float64
 10  V10     263383 non-null  float64
 11  V11     263383 non-null  float64
 12  V12     263383 non-null  float64
 13  V13     263383 non-null  float64
 14  V14     263383 non-null  float64
 15  V15     263383 non-null  float64
 16  V16     263383 non-null  float64
 17  V17     263383 non-null  float64
 18  V18     263383 non-null  float64
 19  V19     263383 non-null  float64
 20  V20     263382 non-null  float64
 21  V21     263382 non-null  float64
 22  V22     263382 non-null  float64
 23  V23     263382 non-null  float64
 24  V24     263382 non-null  float64
 25  V25     263382 non-null  float64
 26  V26     263382 non-null  float64
 27  V27     263382 non-null  float64
 28  V28     263382 non-null  float64
 29  Amount  263382 non-null  float64
 30  Class   263382 non-null  float64
dtypes: float64(31)
memory usage: 62.3 MB

In [ ]:
#checking the no of missing value in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#Distribution of legit transaction and fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    262903
1.0       479
Name: Class, dtype: int64

This dataset is highly unbalanced

0 ---> Normal Transaction          1  ---> fraudulent transaction

In [ ]:
# seperating the data for the analysis
# here we classify the dataset in two variabl seperatily in fraud and ligit
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(262903, 31)
(479, 31)

In [ ]:
# statical measures of the data
legit.Amount.describe()

count    262903.000000
mean         89.845178
std         249.109368
min           0.000000
25%           5.990000
50%          22.800000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     479.000000
mean      121.661566
std       258.174418
min         0.000000
25%         1.000000
50%         8.640000
75%       105.350000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare the values for the both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,89027.227590,-0.008234,-0.023046,0.072246,0.005348,-0.018343,0.013417,-0.000608,-0.000743,0.004832,...,0.001558,-0.001677,-0.005996,-0.003218,0.001443,0.012261,0.001219,-0.000939,0.000736,89.845178
1.0,78406.569937,-4.846113,3.715051,-7.127917,4.616589,-3.251643,-1.401041,-5.667089,0.613703,-2.618765,...,0.372532,0.739000,0.000857,-0.050309,-0.109481,0.045793,0.047321,0.162316,0.076265,121.661566

In [ ]:
credit_card_data.shape

(263383, 31)

Under_Sampling

Build a sample dataset containing similar distribution of normal transactions ans Fraudulent transactions

Number of fraud transaction = 88

In [ ]:
# here we store all (88) legit data in legit_sample variable
legit_sample = legit.sample(n=479*8)

In [ ]:
legit_sample.shape

(3832, 31)

In [ ]:
fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1.0
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262560,160537.0,0.567539,3.309385,-6.631268,6.394574,-0.054172,-2.396535,-2.792489,0.514811,-3.541780,...,0.614221,-0.365047,-0.180409,-0.523271,0.645054,0.246466,0.902675,0.473571,4.69,1.0
262826,160665.0,-0.417340,4.700055,-7.521767,7.671884,0.260821,-2.646693,-2.854432,0.958783,-4.588536,...,0.622200,-0.437708,-0.090358,-0.742802,-0.312361,0.502575,0.821390,0.372379,0.77,1.0
263080,160791.0,2.132386,0.705608,-3.530759,0.514779,1.527175,-1.716268,1.132791,-0.574214,0.128904,...,0.163739,0.703910,-0.245076,0.460049,0.920281,-0.216586,-0.026219,-0.025001,1.00,1.0
263274,160870.0,-0.644278,5.002352,-8.252739,7.756915,-0.216267,-2.751496,-3.358857,1.406268,-4.403852,...,0.587728,-0.605759,0.033746,-0.756170,-0.008172,0.532772,0.663970,0.192067,0.77,1.0
263324,160895.0,-0.848290,2.719882,-6.199070,3.044437,-3.301910,-1.992117,-3.734902,1.520079,-2.548788,...,1.125229,0.805258,0.199119,0.035206,0.012159,0.601658,0.137468,-0.171397,127.14,1.0

In [ ]:
fraud.shape

(479, 31)

Concatenating two dataframes

In [ ]:
new_dataset = pd.concat([legit_sample , fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
186235,127011.0,1.944446,-1.377283,-0.742823,-0.863683,-1.063918,-0.396311,-0.867971,-0.172793,0.050383,...,0.443991,1.064169,-0.079724,-0.589228,-0.135559,-0.042404,-0.005742,-0.025996,149.00,0.0
129209,78994.0,1.177430,0.613589,-0.366778,1.061900,0.497508,-0.197488,0.158662,0.020992,-0.432660,...,0.014126,0.147322,-0.151481,-0.396868,0.656930,-0.297398,0.048888,0.035898,1.00,0.0
262638,160573.0,2.070055,-1.101971,-0.359227,-0.780962,-1.321718,-0.753448,-1.029004,-0.137120,0.091082,...,0.431793,1.222792,0.102374,0.033235,-0.225486,-0.068264,0.012902,-0.037201,54.00,0.0
142537,84778.0,-0.945290,0.995109,1.242071,1.066201,0.578870,1.937812,-0.123397,1.126864,-0.879584,...,0.169818,0.658474,-0.103963,-0.998513,-0.138542,-0.106469,0.076041,0.020364,5.15,0.0
66923,52278.0,1.273903,-0.507862,0.485760,0.205980,-1.002257,-0.469026,-0.454393,-0.029726,-0.556472,...,-0.476934,-0.729732,0.098387,0.394614,0.325429,0.380616,0.005691,0.012206,14.00,0.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    3832
1.0     479
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,89080.995825,0.037425,-0.015925,0.064308,0.009243,-0.038162,-0.011361,0.009113,-0.022204,0.017070,...,-0.000713,-0.003191,-0.004146,-0.027368,-0.015815,0.026028,-0.004306,-0.001855,-0.000891,90.340645
1.0,78406.569937,-4.846113,3.715051,-7.127917,4.616589,-3.251643,-1.401041,-5.667089,0.613703,-2.618765,...,0.372532,0.739000,0.000857,-0.050309,-0.109481,0.045793,0.047321,0.162316,0.076265,121.661566

In [ ]:
new_dataset.shape

(4311, 31)

Spliting the data into Features & Targets

In [ ]:
# now we have to predict the class ( class = 1-> fraud and =0-> legit) so store class in y and rest of all put in the x varible (by dropping class from the data set)
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
186235,127011.0,1.944446,-1.377283,-0.742823,-0.863683,-1.063918,-0.396311,-0.867971,-0.172793,0.050383,...,0.326341,0.443991,1.064169,-0.079724,-0.589228,-0.135559,-0.042404,-0.005742,-0.025996,149.00
129209,78994.0,1.177430,0.613589,-0.366778,1.061900,0.497508,-0.197488,0.158662,0.020992,-0.432660,...,-0.068976,0.014126,0.147322,-0.151481,-0.396868,0.656930,-0.297398,0.048888,0.035898,1.00
262638,160573.0,2.070055,-1.101971,-0.359227,-0.780962,-1.321718,-0.753448,-1.029004,-0.137120,0.091082,...,0.071038,0.431793,1.222792,0.102374,0.033235,-0.225486,-0.068264,0.012902,-0.037201,54.00
142537,84778.0,-0.945290,0.995109,1.242071,1.066201,0.578870,1.937812,-0.123397,1.126864,-0.879584,...,-0.214389,0.169818,0.658474,-0.103963,-0.998513,-0.138542,-0.106469,0.076041,0.020364,5.15
66923,52278.0,1.273903,-0.507862,0.485760,0.205980,-1.002257,-0.469026,-0.454393,-0.029726,-0.556472,...,-0.613002,-0.476934,-0.729732,0.098387,0.394614,0.325429,0.380616,0.005691,0.012206,14.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262560,160537.0,0.567539,3.309385,-6.631268,6.394574,-0.054172,-2.396535,-2.792489,0.514811,-3.541780,...,0.555412,0.614221,-0.365047,-0.180409,-0.523271,0.645054,0.246466,0.902675,0.473571,4.69
262826,160665.0,-0.417340,4.700055,-7.521767,7.671884,0.260821,-2.646693,-2.854432,0.958783,-4.588536,...,0.832035,0.622200,-0.437708,-0.090358,-0.742802,-0.312361,0.502575,0.821390,0.372379,0.77
263080,160791.0,2.132386,0.705608,-3.530759,0.514779,1.527175,-1.716268,1.132791,-0.574214,0.128904,...,-0.211167,0.163739,0.703910,-0.245076,0.460049,0.920281,-0.216586,-0.026219,-0.025001,1.00
263274,160870.0,-0.644278,5.002352,-8.252739,7.756915,-0.216267,-2.751496,-3.358857,1.406268,-4.403852,...,0.816558,0.587728,-0.605759,0.033746,-0.756170,-0.008172,0.532772,0.663970,0.192067,0.77
263324,160895.0,-0.848290,2.719882,-6.199070,3.044437,-3.301910,-1.992117,-3.734902,1.520079,-2.548788,...,0.319576,1.125229,0.805258,0.199119,0.035206,0.012159,0.601658,0.137468,-0.171397,127.14

In [ ]:
print(Y)

186235    0.0
129209    0.0
262638    0.0
142537    0.0
66923     0.0
         ...
262560    1.0
262826    1.0
263080    1.0
263274    1.0
263324    1.0
Name: Class, Length: 4311, dtype: float64

Split the data into train data and the test data

In [ ]:
# divide the dataset for testing and training , here we use 20% data for test and 80% data for train
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 , stratify=Y , random_state=42)

In [ ]:
print(X.shape , X_train.shape , X_test.shape)

(4311, 30) (3448, 30) (863, 30)

Model training

Logistics Regression

In [ ]:
# Now from here we start prediction with Logistics regression
model = LogisticRegression()

In [ ]:
# training the Logistic regression Model with training data , so that we can test the model
model.fit(X_train , Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , Y_train)

In [ ]:
print('Accuracy on training data : ',training_data_accuracy )

Accuracy on training data :  0.978538283062645

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on test data : ',test_data_accuracy )

Accuracy on test data :  0.9710312862108922

## f1 score

In [ ]:
from sklearn.metrics import f1_score
f1 = f1_score(Y_test, X_test_prediction, average='binary')
f1

0.8648648648648649

## Decision tree

In [ ]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train , Y_train)

In [ ]:
# accuracy on training data
X_train_prediction = clf.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , Y_train)
print('Accuracy on training data : ',training_data_accuracy )

Accuracy on training data :  1.0

In [ ]:
#accuracy on test data
X_test_prediction = clf.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy on test data : ',test_data_accuracy )

Accuracy on test data :  0.9652375434530707

In [ ]:
X_test_prediction = np.array(X_test_prediction , dtype = int)

In [ ]:
Y_test = np.array(Y_test , dtype = int)

In [ ]:
f1 = f1_score(Y_test, X_test_prediction, average='binary')
f1

0.845360824742268